config/routes.rb
Dct::Application.routes.draw do

  root 'welcome#index'

  match "/services" => "welcome#services", :via => [:get]
  match "/about" => "welcome#about", :via => [:get]
  match "/faq" => "welcome#faq", :via => [:get]
  match "/contact" => "welcome#contact", :via => [:get]

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title class='col-md-8 col-md-offset-2'>Durrable Computer Technology</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<div class='container'>
		<div class='col-md-10 col-md-offset-1'>
		  <img src='http://dct.bz/DCT/Welcome_files/shapeimage_1.png' class="img-responsive" alt="Responsive image">
		  <nav class="navbar navbar-default" role="navigation">
			  <!-- Brand and toggle get grouped for better mobile display -->
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="/">Home</a>
			    <ul class="nav navbar-nav">
				    <li class="<%= 'active' if current_page?(services_path) %>"><a href="/services">Services</a></li>
				  </ul>
			  </div>

		    <ul class="nav navbar-nav navbar-right">
		      <!-- Collect the nav links, forms, and other content for toggling -->
				  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				    <ul class="nav navbar-nav">
				      <li class="<%= 'active' if current_page?(about_path) %>"><a href="/about">About Me</a></li>
				      <li class="<%= 'active' if current_page?(faq_path) %>"><a href="/faq">FAQ</a></li>
				      <li class="<%= 'active' if current_page?(contact_path) %>"><a href="/contact">Contact Me</a></li>
				    </ul>
        </ul>
			</nav>
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Experience You Can Trust</h1>

	<p>		Richard Durr at Durrable Computer Technology has been helping local Indian River County companies and individuals with their computers since 1992. </p>
	
	<p>I’ve owned my own company and I’ve worked for a number of different types of companies so I understand computers and the software necessary to make companies and individuals more productive. 
	I got my start with computers back in the mid-1980’s in Silicon Valley in California and I have been working with both Microsoft Windows as well as Apple Macintosh computer systems ever since.
	I thoroughly enjoy working with people to solve their computer problems and I have the patience and experience to solve problems.
	I’ll do my best to make you a happy client.</p>

app/views/welcome/faq.html.erb
<h1>Frequent Asked Questions</h1>
<p>
	This section will seek to answer your questions regarding all things relating to computers.  Hopefully, this will become a valuable resource in helping you get the most out of your computer experience.  Your feedback is welcome.
</p>

app/views/welcome/index.html.erb
<div class='col-md-8'>
	<h1>Welcome</h1>
	<p> 
		“Computers are probably the most unfriendly devices that we have to deal with on a daily basis.”  “When computers are working correctly they are wonderful communication and information tools but when they aren’t, computers can be so frustrating.”  
	</p>
	<p>Please contact me and I can help you make your computer user experience productive and rewarding, not frustrating.
	</p>
</div>
<div class='col-md-2'>

</div>

app/views/welcome/services.html.erb
<p>Available at Your Home, Office or Remotely</p>